<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"><modelVersion>4.0.0</modelVersion>
<parent><groupId>com.showtell</groupId><artifactId>click-collect-demo</artifactId><version>1.0.0</version><relativePath>../../pom.xml</relativePath></parent>
<artifactId>order-system-api</artifactId><packaging>mule-application</packaging>
<build><plugins><plugin><groupId>org.mule.tools.maven</groupId><artifactId>mule-maven-plugin</artifactId><version>${mule.maven.plugin.version}</version><extensions>true</extensions><configuration><runtimeVersion>${app.runtime}</runtimeVersion></configuration></plugin>
<plugin><groupId>com.mulesoft.munit.tools</groupId><artifactId>munit-maven-plugin</artifactId><version>${munit.version}</version><executions><execution><id>test</id><phase>test</phase><goals><goal>test</goal></goals></execution></executions><configuration><runtimeVersion>${app.runtime}</runtimeVersion></configuration></plugin></plugins></build>
<dependencies><dependency><groupId>org.mule.connectors</groupId><artifactId>mule-http-connector</artifactId><version>1.10.3</version><classifier>mule-plugin</classifier></dependency>
<dependency><groupId>com.mulesoft.munit</groupId><artifactId>munit-runner</artifactId><version>${munit.version}</version><classifier>mule-plugin</classifier><scope>test</scope></dependency>
<dependency><groupId>com.mulesoft.munit</groupId><artifactId>munit-tools</artifactId><version>${munit.version}</version><classifier>mule-plugin</classifier><scope>test</scope></dependency></dependencies></project>