api.name=order-system-api
http.host=127.0.0.1
http.port=8082
backend.host=127.0.0.1
backend.port=8095
inventory.host=127.0.0.1
inventory.port=8081
orders.host=127.0.0.1
orders.port=8082
process.host=127.0.0.1
process.port=8083
release.version=1.0.0
backend.protocol=HTTP
inventory.protocol=HTTP
orders.protocol=HTTP
process.protocol=HTTP
